import { useState, useRef } from 'react';
import { Card, CardContent, CardHeader, CardTitle } from '../../components/common/Card';
import Button from '../../components/common/Button';
import Input from '../../components/common/Input';
import { Download, Printer, ShieldCheck, CalendarRange, Share2, CheckCircle2 } from 'lucide-react';
import html2canvas from 'html2canvas';
import jsPDF from 'jspdf';
import { useAuthStore } from '../../store/authStore';
import toast from 'react-hot-toast';

export default function Certificate() {
  const { user } = useAuthStore();
  const [isGenerating, setIsGenerating] = useState(false);
  const certificateRef = useRef(null);

  const handleDownloadPDF = async () => {
    if (!certificateRef.current) return;
    setIsGenerating(true);
    try {
      const canvas = await html2canvas(certificateRef.current, {
        scale: 2,
        backgroundColor: '#FFFFFF',
        useCORS: true,
      });
      const imgData = canvas.toDataURL('image/png');
      const pdf = new jsPDF({ orientation: 'portrait', unit: 'px', format: [canvas.width / 2, canvas.height / 2] });
      pdf.addImage(imgData, 'PNG', 0, 0, canvas.width / 2, canvas.height / 2);
      pdf.save(`KamaiKitab_Certificate_${user?.name?.replace(/\s+/g, '_') || 'Worker'}.pdf`);
      toast.success('PDF downloaded successfully!');
    } catch (error) {
      toast.error('Failed to generate PDF. Please try again.');
    } finally {
      setIsGenerating(false);
    }
  };

  const handlePrint = () => window.print();

  const handleShare = async () => {
    const shareData = {
      title: 'KamaiKitab Income Certificate',
      text: `Verified income certificate for ${user?.name || 'Gig Worker'} — generated by KamaiKitab.`,
      url: window.location.href,
    };
    if (navigator.share) {
      await navigator.share(shareData);
    } else {
      await navigator.clipboard.writeText(window.location.href);
      toast.success('Certificate link copied to clipboard!');
    }
  };

  const certData = {
    dateRange: 'March 1, 2026 – March 31, 2026',
    totalEarnings: 85400,
    verifiedPct: 92,
    hoursWorked: 142,
    issueDate: new Date().toLocaleDateString('en-PK', { year: 'numeric', month: 'long', day: 'numeric' }),
    certId: 'KK-CRT-89324-A',
    platforms: ['FoodPanda', 'InDrive'],
    workerCategory: 'Delivery Rider',
  };

  return (
    <div className="space-y-6 max-w-4xl mx-auto">
      {/* Toolbar — hidden on print */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 print:hidden">
        <div>
          <h1 className="text-3xl font-display font-bold text-text">Income Certificate</h1>
          <p className="text-text-muted">Generate a verified, printable income report.</p>
        </div>
        <div className="flex gap-2 flex-wrap">
          <Button variant="outline" onClick={handleShare} className="bg-surface">
            <Share2 size={16} className="mr-2" /> Share
          </Button>
          <Button variant="outline" onClick={handlePrint} className="bg-surface">
            <Printer size={16} className="mr-2" /> Print
          </Button>
          <Button onClick={handleDownloadPDF} isLoading={isGenerating}>
            <Download size={16} className="mr-2" /> Download PDF
          </Button>
        </div>
      </div>

      {/* Date Range Picker — hidden on print */}
      <Card className="print:hidden">
        <CardContent className="flex flex-col sm:flex-row gap-4 items-end">
          <Input label="Start Date" type="date" defaultValue="2026-03-01" className="flex-1" />
          <Input label="End Date" type="date" defaultValue="2026-03-31" className="flex-1" />
          <Button variant="secondary" className="w-full sm:w-auto">
            <CalendarRange size={16} className="mr-2" /> Update Range
          </Button>
        </CardContent>
      </Card>

      {/* ── PRINTABLE CERTIFICATE ── */}
      <div className="overflow-x-auto bg-white rounded-2xl shadow-sm border border-border/50 print:border-none print:shadow-none print:rounded-none">
        <div
          ref={certificateRef}
          className="bg-white p-10 sm:p-16 min-w-[680px] print:min-w-0 print:p-8"
          style={{ fontFamily: 'Inter, sans-serif', color: '#1A1A0F' }}
        >
          {/* Certificate Header */}
          <div className="flex justify-between items-start border-b-2 border-[#2D5016] pb-8 mb-8">
            <div className="flex items-center gap-4">
              <div className="w-14 h-14 bg-[#2D5016] rounded-xl flex items-center justify-center text-white font-bold text-2xl">K</div>
              <div>
                <h1 style={{ fontFamily: 'Outfit, sans-serif', fontSize: '28px', fontWeight: 700, color: '#2D5016', margin: 0 }}>
                  KamaiKitab
                </h1>
                <p style={{ fontSize: '11px', fontWeight: 600, letterSpacing: '0.2em', color: '#6B6B5A', textTransform: 'uppercase', marginTop: '4px' }}>
                  Verified Income Certificate
                </p>
              </div>
            </div>
            <div className="text-right">
              <div className="inline-flex items-center gap-2 px-4 py-2 rounded-xl mb-3"
                style={{ background: 'rgba(39, 174, 96, 0.1)', border: '1px solid rgba(39, 174, 96, 0.3)' }}>
                <CheckCircle2 size={16} color="#27AE60" />
                <span style={{ fontSize: '13px', fontWeight: 700, color: '#27AE60' }}>Community Verified</span>
              </div>
              <p style={{ fontSize: '12px', color: '#6B6B5A', display: 'block' }}>Cert ID: {certData.certId}</p>
              <p style={{ fontSize: '12px', color: '#6B6B5A', display: 'block' }}>Issued: {certData.issueDate}</p>
            </div>
          </div>

          {/* Worker Info */}
          <div className="grid grid-cols-2 gap-8 mb-10">
            <div>
              <p style={{ fontSize: '11px', color: '#6B6B5A', fontWeight: 700, textTransform: 'uppercase', letterSpacing: '0.1em', marginBottom: '6px' }}>Issued To</p>
              <p style={{ fontSize: '22px', fontWeight: 700, color: '#1A1A0F', marginBottom: '4px' }}>{user?.name || 'Ahmad Khan'}</p>
              <p style={{ fontSize: '13px', color: '#6B6B5A' }}>{user?.email || 'ahmad.khan@example.com'}</p>
              <p style={{ fontSize: '13px', color: '#6B6B5A', marginTop: '4px' }}>Category: {certData.workerCategory}</p>
              <p style={{ fontSize: '13px', color: '#6B6B5A' }}>Platforms: {certData.platforms.join(', ')}</p>
            </div>
            <div className="text-right">
              <p style={{ fontSize: '11px', color: '#6B6B5A', fontWeight: 700, textTransform: 'uppercase', letterSpacing: '0.1em', marginBottom: '6px' }}>Period Covered</p>
              <p style={{ fontSize: '16px', fontWeight: 600, color: '#1A1A0F' }}>{certData.dateRange}</p>
            </div>
          </div>

          {/* Earnings Summary Box */}
          <div style={{ background: '#F5F0E8', borderRadius: '16px', padding: '40px', marginBottom: '40px', border: '1px solid #E5DDD0' }}>
            <p style={{ textAlign: 'center', fontSize: '11px', fontWeight: 700, color: '#6B6B5A', textTransform: 'uppercase', letterSpacing: '0.2em', marginBottom: '24px' }}>
              Verified Earnings Summary
            </p>
            <div style={{ textAlign: 'center', marginBottom: '32px' }}>
              <span style={{ fontSize: '16px', color: '#6B6B5A', fontWeight: 700, verticalAlign: 'middle' }}>Rs. </span>
              <span style={{ fontSize: '56px', fontWeight: 800, color: '#2D5016', fontFamily: 'Outfit, sans-serif' }}>
                {certData.totalEarnings.toLocaleString()}
              </span>
            </div>
            <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr 1fr', gap: '24px', textAlign: 'center', borderTop: '1px solid #E5DDD0', paddingTop: '24px' }}>
              <div>
                <p style={{ fontSize: '12px', color: '#6B6B5A', marginBottom: '4px' }}>Total Hours Logged</p>
                <p style={{ fontSize: '22px', fontWeight: 700, color: '#1A1A0F' }}>{certData.hoursWorked}h</p>
              </div>
              <div style={{ borderLeft: '1px solid #E5DDD0', borderRight: '1px solid #E5DDD0' }}>
                <p style={{ fontSize: '12px', color: '#6B6B5A', marginBottom: '4px' }}>Verification Rate</p>
                <p style={{ fontSize: '22px', fontWeight: 700, color: '#27AE60' }}>{certData.verifiedPct}%</p>
              </div>
              <div>
                <p style={{ fontSize: '12px', color: '#6B6B5A', marginBottom: '4px' }}>Avg. Hourly Rate</p>
                <p style={{ fontSize: '22px', fontWeight: 700, color: '#1A1A0F' }}>
                  Rs. {Math.round(certData.totalEarnings / certData.hoursWorked)}
                </p>
              </div>
            </div>
          </div>

          {/* Declaration */}
          <div style={{ marginBottom: '48px' }}>
            <p style={{ fontSize: '11px', fontWeight: 700, color: '#6B6B5A', textTransform: 'uppercase', letterSpacing: '0.1em', marginBottom: '10px' }}>
              Declaration of Authenticity
            </p>
            <p style={{ fontSize: '12px', color: '#6B6B5A', lineHeight: '1.8' }}>
              This document is generated by KamaiKitab (FairGig) and certifies the income summary above. Earnings marked as verified ({certData.verifiedPct}% of total volume) have been authenticated against digital platform receipts by community peer-verifiers. This certificate may be presented to landlords, financial institutions, or family members as evidence of gig-economy income. KamaiKitab is honest about what it can verify: only records with uploaded platform screenshots and verifier approval carry the "Verified" status.
            </p>
          </div>

          {/* Signature Row */}
          <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-end', borderTop: '1px solid #E5DDD0', paddingTop: '32px' }}>
            <div style={{ textAlign: 'center' }}>
              <div style={{ width: '200px', borderBottom: '2px solid #2D5016', marginBottom: '8px', height: '40px', position: 'relative' }}>
                <svg style={{ position: 'absolute', bottom: '8px', left: '16px', width: '120px', height: '28px', opacity: 0.7 }} viewBox="0 0 120 30" fill="none" stroke="#2D5016" strokeWidth="1.5">
                  <path d="M5,20 Q20,5 35,18 T65,16 T95,20 T115,18" />
                </svg>
              </div>
              <p style={{ fontSize: '12px', fontWeight: 700, color: '#1A1A0F' }}>Digital Signature</p>
              <p style={{ fontSize: '11px', color: '#6B6B5A' }}>KamaiKitab Validation System</p>
            </div>
            <div style={{ textAlign: 'center' }}>
              <div style={{ width: '88px', height: '88px', border: '2px solid #2D5016', borderRadius: '12px', display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', background: 'rgba(45,80,22,0.05)' }}>
                <CheckCircle2 size={24} color="#2D5016" />
                <p style={{ fontSize: '9px', fontWeight: 800, color: '#2D5016', textTransform: 'uppercase', letterSpacing: '0.05em', marginTop: '4px', lineHeight: 1.3 }}>Valid<br/>Record</p>
              </div>
            </div>
          </div>

          {/* Print footer */}
          <div style={{ marginTop: '32px', textAlign: 'center', fontSize: '10px', color: '#A0A090' }}>
            Generated by KamaiKitab (FairGig) · Cert ID: {certData.certId} · {certData.issueDate}
          </div>
        </div>
      </div>
    </div>
  );
}
